import React, { useEffect, useState, useCallback, useMemo } from 'react';
import { BoardItem, ConflictThreat, ExtensionMessage, GHLabel, LinkedPR, PRFile, RunwayConfig, RunwayData } from '../src/types';
import { ColumnGroup } from './components/ColumnGroup';
import { DetailPanel } from './components/DetailPanel';
import { LaunchpadView } from './components/LaunchpadView';
import { SettingsPanel } from './components/SettingsPanel';

// Acquire vscode API once (must not be called more than once)
declare function acquireVsCodeApi(): {
  postMessage(msg: unknown): void;
  getState(): unknown;
  setState(state: unknown): void;
};
const vscodeApi = acquireVsCodeApi();

type FilterTab = 'dashboard' | 'all' | 'prs' | 'issues' | 'milestones';

// CSS is loaded externally via out/styles.css (see SprintHubPanel._buildHtml)


// Column metadata
const COLUMN_CONFIG: Record<string, { color: string; emoji: string }> = {
  'TODO':                  { color: '#585b70', emoji: '○' },
  'In Progress':           { color: '#89b4fa', emoji: '◑' },
  'Ready For Review':      { color: '#fab387', emoji: '👁' },
  'Ready For QA':          { color: '#f9e2af', emoji: '🔍' },
  'QA Done':               { color: '#a6e3a1', emoji: '✓' },
  'Done':                  { color: '#74c7ec', emoji: '✓✓' },
  'Blocked':               { color: '#f38ba8', emoji: '⊘' },
  'Needs Grooming':        { color: '#cba6f7', emoji: '✂' },
  'Grooming in Progress':  { color: '#b4befe', emoji: '⚙' },
  'Grooming to Review':    { color: '#f5c2e7', emoji: '⬡' },
};

function getColumnConfig(name: string) {
  return COLUMN_CONFIG[name] ?? { color: '#6c7086', emoji: '·' };
}

// ── Lightweight markdown renderer for the standup output ──────────────────────
// Only handles the exact patterns generated by generateStandupMarkdown.

function parseInlineMarkdown(text: string, onOpenUrl: (url: string) => void, key: string): React.ReactNode {
  const nodes: React.ReactNode[] = [];
  const linkRe = /\[([^\]]+)\]\(([^)]+)\)/g;
  let cursor = 0;
  let m: RegExpExecArray | null;

  while ((m = linkRe.exec(text)) !== null) {
    if (m.index > cursor) {
      nodes.push(parseItalic(text.slice(cursor, m.index), `${key}-t${cursor}`));
    }
    const url = m[2];
    nodes.push(
      <a key={`${key}-l${m.index}`} href="#" className="standup-link"
        onClick={(e) => { e.preventDefault(); onOpenUrl(url); }}>
        {m[1]}
      </a>
    );
    cursor = m.index + m[0].length;
  }
  if (cursor < text.length) nodes.push(parseItalic(text.slice(cursor), `${key}-t${cursor}`));
  return nodes.length === 1 ? nodes[0] : <React.Fragment key={key}>{nodes}</React.Fragment>;
}

function parseItalic(text: string, key: string): React.ReactNode {
  const nodes: React.ReactNode[] = [];
  const re = /\*([^*]+)\*/g;
  let cursor = 0;
  let m: RegExpExecArray | null;
  while ((m = re.exec(text)) !== null) {
    if (m.index > cursor) nodes.push(text.slice(cursor, m.index));
    nodes.push(<em key={`${key}-i${m.index}`} className="standup-em">{m[1]}</em>);
    cursor = m.index + m[0].length;
  }
  if (cursor < text.length) nodes.push(text.slice(cursor));
  return nodes.length === 0 ? text : nodes.length === 1 ? nodes[0] : <React.Fragment key={key}>{nodes}</React.Fragment>;
}

function renderStandupMarkdown(md: string, onOpenUrl: (url: string) => void): React.ReactNode {
  const lines = md.split('\n');
  const els: React.ReactNode[] = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith('## ')) {
      els.push(<h2 key={i} className="standup-h2">{line.slice(3)}</h2>);
    } else if (line.startsWith('### ')) {
      els.push(<h3 key={i} className="standup-h3">{parseInlineMarkdown(line.slice(4), onOpenUrl, `${i}`)}</h3>);
    } else if (line.startsWith('- ')) {
      els.push(
        <div key={i} className="standup-li">
          <span className="standup-bullet">•</span>
          <span>{parseInlineMarkdown(line.slice(2), onOpenUrl, `${i}`)}</span>
        </div>
      );
    } else if (line.trim() === '') {
      els.push(<div key={i} className="standup-spacer" />);
    } else {
      els.push(<p key={i} className="standup-p">{parseInlineMarkdown(line, onOpenUrl, `${i}`)}</p>);
    }
  }
  return <div className="standup-rendered">{els}</div>;
}

// ──────────────────────────────────────────────────────────────────────────────

export function App() {
  const [state, setState] = useState<'loading' | 'error' | 'data'>('loading');
  const [data, setData] = useState<RunwayData | null>(null);
  const [config, setConfig] = useState<RunwayConfig | null>(null);
  const [errorMsg, setErrorMsg] = useState('');
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [search, setSearch] = useState('');
  const [tab, setTab] = useState<FilterTab>('dashboard');
  const [sprintFilter, setSprintFilter] = useState<string | null>(null);
  const [detailItem, setDetailItem] = useState<BoardItem | null>(null);
  const [linkedPRs, setLinkedPRs] = useState<LinkedPR[] | null>(null);
  const [settingsOpen, setSettingsOpen] = useState(false);
  // Phase 1: PR file deep linking
  const [prFiles, setPrFiles] = useState<PRFile[] | null>(null);
  // Phase 2: conflict threats
  const [conflictThreats, setConflictThreats] = useState<ConflictThreat[]>([]);
  // Phase 3: standup
  const [standupMarkdown, setStandupMarkdown] = useState<string | null>(null);
  const [standupLoading, setStandupLoading] = useState(false);
  const [standupView, setStandupView] = useState<'view' | 'markdown'>('view');
  // Phase 3: repo labels cache keyed by "owner/repo"
  const [repoLabelsCache, setRepoLabelsCache] = useState<Map<string, GHLabel[]>>(new Map());
  // v2: CODEOWNERS cache keyed by "owner/repo"
  const [codeownersCache, setCodeownersCache] = useState<Map<string, Array<{ pattern: string; owners: string[] }>>>(new Map());

  useEffect(() => {
    const handler = (event: MessageEvent) => {
      const msg = event.data as ExtensionMessage;
      switch (msg.type) {
        case 'loading':
          setIsRefreshing(true);
          if (state !== 'data') setState('loading');
          break;
        case 'data':
          setData(msg.payload);
          setState('data');
          setIsRefreshing(false);
          // Auto-select the latest sprint (sprints are sorted numeric desc so [0] is the highest)
          if (msg.payload.sprints.length > 0) {
            setSprintFilter((prev) => prev ?? msg.payload.sprints[0]);
          }
          break;
        case 'error':
          setErrorMsg(msg.message);
          setState('error');
          setIsRefreshing(false);
          break;
        case 'config':
          setConfig(msg.payload);
          break;
        case 'linkedPRs':
          setLinkedPRs(msg.prs);
          break;
        case 'itemBody':
          setDetailItem((prev) => prev && prev.id === msg.itemId ? { ...prev, body: msg.body } : prev);
          break;
        // Phase 1: PR files
        case 'prFiles':
          setPrFiles(msg.files);
          break;
        // Phase 2: conflict threats
        case 'conflictThreats':
          setConflictThreats(msg.threats);
          break;
        // Phase 3: standup
        case 'standup':
          setStandupMarkdown(msg.markdown);
          setStandupLoading(false);
          break;
        // Phase 3: metadata confirmed
        case 'metadataUpdated':
          setDetailItem((prev) =>
            prev && prev.id === msg.itemId
              ? { ...prev, labels: msg.labels, assignees: msg.assignees }
              : prev
          );
          break;
        // Phase 3: repo labels loaded
        case 'repoLabels': {
          const cacheKey = `${msg.owner}/${msg.repo}`;
          setRepoLabelsCache((prev) => new Map(prev).set(cacheKey, msg.labels));
          break;
        }
        // v2: draft converted to ready
        case 'prReadied':
          setDetailItem((prev) => prev && prev.id === msg.itemId ? { ...prev, isDraft: false } : prev);
          break;
        // v2: PR merged
        case 'prMerged':
          setDetailItem((prev) => prev && prev.id === msg.itemId ? { ...prev, state: 'MERGED' } : prev);
          break;
        // v2: CODEOWNERS loaded
        case 'codeowners': {
          const coKey = `${msg.owner}/${msg.repo}`;
          setCodeownersCache((prev) => new Map(prev).set(coKey, msg.entries));
          break;
        }
      }
    };

    window.addEventListener('message', handler);
    // Request current config on mount
    vscodeApi.postMessage({ type: 'getConfig' });
    return () => window.removeEventListener('message', handler);
  }, [state]);

  const handleRefresh = useCallback(() => {
    setIsRefreshing(true);
    vscodeApi.postMessage({ type: 'refresh' });
  }, []);

  const handleOpenUrl = useCallback((url: string) => {
    vscodeApi.postMessage({ type: 'openUrl', url });
  }, []);

  const handleSaveConfig = useCallback((cfg: RunwayConfig) => {
    vscodeApi.postMessage({ type: 'updateConfig', payload: cfg });
    setConfig(cfg);
  }, []);

  // Apply visual mode classes on both body and #root.
  // body → needed for body-level background/color overrides.
  // #root → needed for position:fixed overlay descendants (detail panel, settings modal).
  useEffect(() => {
    const root = document.getElementById('root');
    if (!root) return;
    const isLight = config?.theme === 'light';
    const isColorBlind = config?.colorBlind ?? false;
    const isLiquidGlass = config?.liquidGlass ?? false;
    root.classList.toggle('liquid-glass', isLiquidGlass);
    root.classList.toggle('light-theme', isLight);
    root.classList.toggle('color-blind', isColorBlind);
    document.body.classList.toggle('liquid-glass', isLiquidGlass);
    document.body.classList.toggle('light-theme', isLight);
    document.body.classList.toggle('color-blind', isColorBlind);
  }, [config?.liquidGlass, config?.theme, config?.colorBlind]);

  const filteredGroups = useMemo((): Record<string, BoardItem[]> => {
    if (!data) return {};
    const q = search.toLowerCase().trim();

    const result: Record<string, BoardItem[]> = {};
    for (const col of data.columns) {
      let items = data.groups[col] ?? [];

      // Tab filter (milestones tab shows all types in its own view)
      if (tab === 'prs') items = items.filter((i) => i.type === 'PULL_REQUEST');
      if (tab === 'issues') items = items.filter((i) => i.type === 'ISSUE');

      // Sprint filter
      if (sprintFilter) items = items.filter((i) => i.sprint === sprintFilter);

      // Search filter
      if (q) {
        items = items.filter(
          (i) =>
            i.title.toLowerCase().includes(q) ||
            String(i.number).includes(q) ||
            i.author.login.toLowerCase().includes(q) ||
            i.labels.some((l) => l.name.toLowerCase().includes(q)) ||
            i.repository.toLowerCase().includes(q) ||
            (i.headRefName ?? '').toLowerCase().includes(q) ||
            (i.sprint ?? '').toLowerCase().includes(q) ||
            (i.milestone?.title ?? '').toLowerCase().includes(q)
        );
      }

      result[col] = items;
    }
    return result;
  }, [data, search, tab, sprintFilter]);

  const milestoneGroups = useMemo((): Record<string, BoardItem[]> => {
    if (!data) return {};
    const allItems = Object.values(data.groups).flat();
    const q = search.toLowerCase().trim();

    let items = allItems;
    if (sprintFilter) items = items.filter((i) => i.sprint === sprintFilter);
    if (q) {
      items = items.filter(
        (i) =>
          i.title.toLowerCase().includes(q) ||
          String(i.number).includes(q) ||
          i.author.login.toLowerCase().includes(q) ||
          i.labels.some((l) => l.name.toLowerCase().includes(q)) ||
          (i.milestone?.title ?? '').toLowerCase().includes(q)
      );
    }

    const groups: Record<string, BoardItem[]> = {};
    for (const item of items) {
      const key = item.milestone?.title ?? '(No Milestone)';
      if (!groups[key]) groups[key] = [];
      groups[key].push(item);
    }
    return groups;
  }, [data, search, sprintFilter]);

  const counts = useMemo(() => {
    if (!data) return { all: 0, prs: 0, issues: 0 };
    let all = Object.values(data.groups).flat();
    if (sprintFilter) all = all.filter((i) => i.sprint === sprintFilter);
    return {
      all: all.length,
      prs: all.filter((i) => i.type === 'PULL_REQUEST').length,
      issues: all.filter((i) => i.type === 'ISSUE').length,
    };
  }, [data, sprintFilter]);

  const handleSelectItem = useCallback((item: BoardItem) => {
    setDetailItem(item);
    setLinkedPRs(null);
    setPrFiles(null);

    if (item.body === undefined) {
      vscodeApi.postMessage({
        type: 'fetchBody',
        itemId: item.id,
        owner: item.repositoryOwner,
        repo: item.repository,
        number: item.number,
        isIssue: item.type === 'ISSUE',
      });
    }
    if (item.type === 'ISSUE') {
      vscodeApi.postMessage({
        type: 'fetchLinkedPRs',
        itemId: item.id,
        owner: item.repositoryOwner,
        repo: item.repository,
        issueNumber: item.number,
      });
    }
    // Phase 1: fetch changed files for PRs
    if (item.type === 'PULL_REQUEST') {
      const prKey = `${item.repositoryOwner}/${item.repository}#${item.number}`;
      vscodeApi.postMessage({
        type: 'fetchPRFiles',
        prKey,
        owner: item.repositoryOwner,
        repo: item.repository,
        prNumber: item.number,
      });
      // v2: fetch CODEOWNERS if not already cached
      vscodeApi.postMessage({
        type: 'fetchCodeowners',
        owner: item.repositoryOwner,
        repo: item.repository,
      });
    }
  }, []);

  // Phase 1: open PR file in editor
  const handleOpenPRFile = useCallback((owner: string, repo: string, prNumber: number, filename: string, patch?: string) => {
    vscodeApi.postMessage({ type: 'openPRFile', owner, repo, prNumber, filename, patch });
  }, []);

  // Phase 1: work on this branch
  const handleWorkOnThis = useCallback((branchName: string, owner: string, repo: string) => {
    vscodeApi.postMessage({ type: 'workOnThis', branchName, owner, repo });
  }, []);

  // Phase 3: generate standup
  const handleGenerateStandup = useCallback(() => {
    if (!data?.viewerLogin) return;
    setStandupLoading(true);
    setStandupMarkdown(null);
    setStandupView('view');
    vscodeApi.postMessage({ type: 'generateStandup', viewerLogin: data.viewerLogin });
  }, [data?.viewerLogin]);

  // Phase 3: metadata update
  const handleUpdateMetadata = useCallback((itemId: string, owner: string, repo: string, issueNumber: number, labels?: string[], assignees?: string[]) => {
    vscodeApi.postMessage({ type: 'updateMetadata', itemId, owner, repo, issueNumber, labels, assignees });
  }, []);

  // Phase 3: fetch repo labels
  const handleFetchRepoLabels = useCallback((owner: string, repo: string) => {
    vscodeApi.postMessage({ type: 'fetchRepoLabels', owner, repo });
  }, []);

  // v2: convert draft to ready
  const handleConvertDraftToReady = useCallback((itemId: string, owner: string, repo: string, prNumber: number) => {
    vscodeApi.postMessage({ type: 'convertDraftToReady', itemId, owner, repo, prNumber });
  }, []);

  // v2: merge PR
  const handleMergePR = useCallback((itemId: string, owner: string, repo: string, prNumber: number, mergeMethod: 'merge' | 'squash' | 'rebase') => {
    vscodeApi.postMessage({ type: 'mergePR', itemId, owner, repo, prNumber, mergeMethod });
  }, []);

  const formatLastUpdated = (iso: string) => {
    const d = new Date(iso);
    return `Last refreshed at ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  };

  return (
    <>
      {/* SVG glass refraction filter — referenced via CSS filter: url(#glass-distort) */}
      <svg className="glass-filter-svg" aria-hidden="true">
        <defs>
          <filter id="glass-distort" x="-20%" y="-20%" width="140%" height="140%" colorInterpolationFilters="linearRGB">
            <feTurbulence type="fractalNoise" baseFrequency="0.012 0.008" numOctaves="4" seed="5" result="noise" />
            <feDisplacementMap in="SourceGraphic" in2="noise" scale="28" xChannelSelector="R" yChannelSelector="G" />
          </filter>
        </defs>
      </svg>

      {/* Header */}
      <div className="header">
        <div className="header-left">
          {/* Rocket icon */}
          <svg width="20" height="20" viewBox="0 0 24 24" fill="none" style={{ color: '#89b4fa' }}>
            <path d="M12 2C12 2 7 6 7 12C7 14.76 8.12 17.27 10 19L12 22L14 19C15.88 17.27 17 14.76 17 12C17 6 12 2 12 2Z" fill="currentColor" opacity="0.9"/>
            <circle cx="12" cy="12" r="2" fill="#13131c"/>
            <path d="M9 19L7 21L5 19" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
            <path d="M15 19L17 21L19 19" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
          </svg>
          <span className="header-title">
            SprintHub
            {data?.projectTitle && (
              <span className="project-name">· {data.projectTitle}</span>
            )}
          </span>
        </div>
        <div className="header-right">
          {data && <span className="total-badge">{data.totalCount} items</span>}
          {/* Phase 3: Standup Generator */}
          {data && (
            <button
              className={`btn${standupLoading ? ' loading' : ''}`}
              onClick={handleGenerateStandup}
              disabled={standupLoading}
              title="Generate daily standup"
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
                <line x1="16" y1="13" x2="8" y2="13"/>
                <line x1="16" y1="17" x2="8" y2="17"/>
                <polyline points="10 9 9 9 8 9"/>
              </svg>
              Standup
            </button>
          )}
          {/* Settings button */}
          <button className="btn" onClick={() => setSettingsOpen(true)} title="Project settings">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="3"/>
              <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>
            </svg>
          </button>
          <button className={`btn${isRefreshing ? ' loading' : ''}`} onClick={handleRefresh}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="23 4 23 10 17 10"/>
              <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
            </svg>
            Refresh
          </button>
        </div>
      </div>

      {/* Toolbar / tabs */}
      <div className="toolbar">
        {(['dashboard', 'all', 'prs', 'issues', 'milestones'] as FilterTab[]).map((t) => {
          const labels: Record<FilterTab, string> = { dashboard: '🚀 Dashboard', all: 'Main Board', prs: 'Pull Requests', issues: 'Issues', milestones: 'Milestones' };
          const tabCounts: Record<FilterTab, number> = {
            dashboard: counts.prs,
            all: counts.all,
            prs: counts.prs,
            issues: counts.issues,
            milestones: data ? Object.keys(milestoneGroups).length : 0,
          };
          return (
            <button
              key={t}
              className={`tab-btn${tab === t ? ' active' : ''}`}
              onClick={() => setTab(t)}
            >
              {labels[t]}
              {t !== 'dashboard' && <span className="tab-count">{tabCounts[t]}</span>}
            </button>
          );
        })}
      </div>

      {/* Phase 2: Conflict Threats Banner */}
      {conflictThreats.length > 0 && (
        <div className="conflict-banner">
          <svg className="conflict-banner-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
            <line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
          </svg>
          <div className="conflict-banner-body">
            <div className="conflict-banner-title">
              {conflictThreats.length} file conflict{conflictThreats.length > 1 ? 's' : ''} detected with open PRs
            </div>
            <div className="conflict-banner-items">
              {conflictThreats.slice(0, 3).map((t, i) => (
                <div key={i} className="conflict-banner-item">
                  <strong>{t.filename}</strong> — also modified in PR #{t.prNumber} by {t.prAuthor}
                </div>
              ))}
              {conflictThreats.length > 3 && (
                <div className="conflict-banner-item">…and {conflictThreats.length - 3} more</div>
              )}
            </div>
          </div>
          <button className="conflict-banner-dismiss" onClick={() => setConflictThreats([])} title="Dismiss">×</button>
        </div>
      )}

      {/* Sprint filter dropdown */}
      {data && data.sprints.length > 0 && (
        <div className="sprint-bar">
          <span className="sprint-label">Sprint</span>
          <select
            className="sprint-select"
            value={sprintFilter ?? ''}
            onChange={(e) => setSprintFilter(e.target.value || null)}
          >
            <option value="">All sprints</option>
            {data.sprints.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
          {sprintFilter && (
            <span className="sprint-active-badge">
              {sprintFilter}
              <button className="sprint-clear-btn" onClick={() => setSprintFilter(null)} title="Clear sprint filter">✕</button>
            </span>
          )}
        </div>
      )}

      {/* Search */}
      <div className="search-wrap">
        <svg className="search-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>
        </svg>
        <input
          className="search-input"
          placeholder={tab === 'milestones' ? 'Search milestones and items…' : 'Search by title, number, author, label, branch, sprint…'}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      {/* Content */}
      <div className="content">
        {state === 'loading' && (
          <div className="center-state">
            <div className="spinner" />
            <span className="state-title">Loading project…</span>
          </div>
        )}

        {state === 'error' && (
          <div className="center-state">
            <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="#f38ba8" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
            </svg>
            <span className="state-title state-err">Failed to load</span>
            <span className="state-sub">{errorMsg}</span>
            <div style={{ display: 'flex', gap: 8 }}>
              <button className="btn" onClick={() => setSettingsOpen(true)}>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <circle cx="12" cy="12" r="3"/>
                  <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>
                </svg>
                Open Settings
              </button>
              <button className="btn" onClick={handleRefresh}>Try again</button>
            </div>
          </div>
        )}

        {state === 'data' && data && (
          <>
            {tab === 'dashboard' ? (
              /* Dashboard view — PRs grouped by action needed */
              <LaunchpadView
                items={data.columns.flatMap((c) => data.groups[c] ?? [])}
                linkedIssuePRs={data.linkedIssuePRs ?? []}
                viewerLogin={data.viewerLogin ?? ''}
                onSelect={handleSelectItem}
                onOpenUrl={handleOpenUrl}
              />
            ) : tab === 'milestones' ? (
              /* Milestones view */
              Object.keys(milestoneGroups).length === 0 ? (
                <div className="milestone-empty">
                  <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#45475a" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M18 4l3 3-3 3"/><path d="M3 7h18"/>
                    <path d="M6 20l-3-3 3-3"/><path d="M21 17H3"/>
                  </svg>
                  No milestones found
                </div>
              ) : (
                Object.entries(milestoneGroups).map(([milestone, items]) => (
                  <ColumnGroup
                    key={milestone}
                    column={milestone}
                    items={items}
                    config={{ color: '#cba6f7', emoji: '⬡' }}
                    onSelect={handleSelectItem}
                    onOpenUrl={handleOpenUrl}
                  />
                ))
              )
            ) : (
              /* Board view */
              data.columns.map((col) => {
                const items = filteredGroups[col] ?? [];
                return (
                  <ColumnGroup
                    key={col}
                    column={col}
                    items={items}
                    config={getColumnConfig(col)}
                    onSelect={handleSelectItem}
                    onOpenUrl={handleOpenUrl}
                  />
                );
              })
            )}
          </>
        )}
      </div>

      {/* Footer */}
      {data && (
        <div className="footer">
          {formatLastUpdated(data.lastUpdated)}
          {sprintFilter && <span style={{ marginLeft: 8, color: '#89b4fa' }}>· Sprint: {sprintFilter}</span>}
        </div>
      )}

      {/* Detail panel */}
      {detailItem && (
        <DetailPanel
          item={detailItem}
          linkedPRs={linkedPRs}
          prFiles={prFiles}
          repoLabels={repoLabelsCache.get(`${detailItem.repositoryOwner}/${detailItem.repository}`) ?? []}
          codeownersEntries={codeownersCache.get(`${detailItem.repositoryOwner}/${detailItem.repository}`) ?? []}
          onClose={() => { setDetailItem(null); setLinkedPRs(null); setPrFiles(null); }}
          actions={{
            onOpenUrl: handleOpenUrl,
            onWorkOnThis: handleWorkOnThis,
            onOpenPRFile: handleOpenPRFile,
            onUpdateMetadata: handleUpdateMetadata,
            onFetchRepoLabels: handleFetchRepoLabels,
            onConvertDraftToReady: handleConvertDraftToReady,
            onMergePR: handleMergePR,
          }}
        />
      )}

      {/* Phase 3: Standup modal */}
      {(standupLoading || standupMarkdown !== null) && (
        <div className="standup-overlay" onClick={(e) => { if (e.target === e.currentTarget) { setStandupMarkdown(null); setStandupLoading(false); } }}>
          <div className="standup-modal">
            <div className="standup-header">
              <span className="standup-title">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#89b4fa" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                </svg>
                Daily Standup
              </span>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                {/* View toggle — only shown when content is ready */}
                {standupMarkdown && (
                  <div className="standup-view-toggle">
                    <button
                      className={`standup-view-btn${standupView === 'view' ? ' active' : ''}`}
                      onClick={() => setStandupView('view')}
                    >
                      View
                    </button>
                    <button
                      className={`standup-view-btn${standupView === 'markdown' ? ' active' : ''}`}
                      onClick={() => setStandupView('markdown')}
                    >
                      Markdown
                    </button>
                  </div>
                )}
                <button className="detail-close-btn" onClick={() => { setStandupMarkdown(null); setStandupLoading(false); }}>
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                  </svg>
                </button>
              </div>
            </div>
            <div className="standup-body">
              {standupLoading && !standupMarkdown && (
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, color: '#6c7086', fontSize: 12 }}>
                  <div style={{ width: 12, height: 12, border: '2px solid #45475a', borderTopColor: '#89b4fa', borderRadius: '50%', animation: 'spin 0.75s linear infinite' }} />
                  Fetching your GitHub activity…
                </div>
              )}
              {standupMarkdown && standupView === 'view' && renderStandupMarkdown(standupMarkdown, handleOpenUrl)}
              {standupMarkdown && standupView === 'markdown' && <pre className="standup-md">{standupMarkdown}</pre>}
            </div>
            {standupMarkdown && (
              <div className="standup-footer">
                <button className="btn" onClick={() => { setStandupMarkdown(null); setStandupLoading(false); }}>Close</button>
                <button
                  className="btn btn-primary"
                  onClick={() => {
                    navigator.clipboard?.writeText(standupMarkdown!).catch(() => undefined);
                  }}
                >
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2"/>
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
                  </svg>
                  Copy Markdown
                </button>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Settings panel */}
      {settingsOpen && config && (
        <SettingsPanel
          config={config}
          onSave={handleSaveConfig}
          onClose={() => setSettingsOpen(false)}
        />
      )}
      {settingsOpen && !config && (
        <SettingsPanel
          config={{ owner: '', projectNumber: 0, ownerType: 'organization', statusFieldName: 'Status', refreshInterval: 5, liquidGlass: false }}
          onSave={handleSaveConfig}
          onClose={() => setSettingsOpen(false)}
        />
      )}
    </>
  );
}
